runtime: php72
runtime_config:
  document_root: Pharmacy-Management

handlers:
- url: /
  script: index.php


- url: /css
  static_dir: css

#- url: /images
#  static_dir: images

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$  

- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js  

- url: /php
  static_dir: php

- url: .*
  script: auto  


env_variables:
  MYSQL_HOST: mysql:unix_socket=/cloudsql/pharmacyms:asia-south1:pharmacytest
  MYSQL_DB: pharmacy
  MYSQL_USER: root
  MYSQL_PASS: 